apiVersion: 1

datasources:
  - name: Zabbix_DB
    type: postgres
    url: postgres-server:5432
    database: zabbix
    user: zabbix
    secureJsonData:
      password: zabbix
    jsonData:
      sslmode: disable
